# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20170611_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text_orig', models.CharField(max_length=500)),
                ('tweet_text_lem', models.CharField(max_length=500)),
                ('tweet_text_stop', models.CharField(max_length=500)),
                ('tweet_date', models.DateField(verbose_name='date tweet published')),
                ('tweet_user', models.CharField(max_length=100)),
            ],
        ),
    ]
