# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet_test',
        ),
    ]
